services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: insparation06/todo_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  telegram_bot:
    image: insparation06/todo_telegram_bot
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  pgdata: