# Generated by Django 5.2.6 on 2025-09-29 23:40

from django.db import migrations, models

import core.generate_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=core.generate_key.generate_primary_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=core.generate_key.generate_primary_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Идентификатор пользователя в Telegram', verbose_name='Telegram User ID')),
                ('title', models.CharField(help_text='Краткое название задачи', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Подробное описание задачи', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания задачи', verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(help_text='Дата и время завершения задачи', verbose_name='Срок выполнения')),
                ('category', models.ManyToManyField(help_text='Связанные категории задачи', to='tasks.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('created_at',),
            },
        ),
    ]
