# Generated by Django 5.2.6 on 2025-09-27 19:09

from django.db import migrations, models

import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=tasks.models.generate_custom_primary_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=tasks.models.generate_custom_primary_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Идентификатор пользователя в Telegram', verbose_name='Telegram User ID')),
                ('title', models.CharField(help_text='Краткое название задачи', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание задачи', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания задачи', verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(help_text='Дата и время завершения задачи', verbose_name='Срок выполнения')),
                ('category', models.ManyToManyField(blank=True, help_text='Связанные категории задачи', to='tasks.category', verbose_name='Категории')),
            ],
        ),
    ]
