# Generated by Django 5.2.6 on 2025-09-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(help_text='Связанные категории задачи', to='tasks.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Подробное описание задачи', verbose_name='Описание'),
        ),
    ]
