# Generated by Django 5.2.6 on 2025-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено уведомление?'),
        ),
    ]
